apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nickmartin1ee7-poi-map-app-dev
  annotations:
    argocd/app-name: nickmartin1ee7-poi-map-app-dev
    backstage.io/kubernetes-id: nickmartin1ee7-poi-map-app
    backstage.io/kubernetes-namespace: nickmartin1ee7
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-deploy/nickmartin1ee7-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/dev-pipelines/ns/nickmartin1ee7/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/k8s/ns/nickmartin1ee7/deployments/nickmartin1ee7-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.a1jxqhzp.eastus2.aroapp.io/#https://github.com/rhdh-deploy/nickmartin1ee7-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://nickmartin1ee7-poi-map-app-nickmartin1ee7.apps.a1jxqhzp.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/nickmartin1ee7"
  system: workshop-system-nickmartin1ee7
  consumesApis:
    - gateway-api-nickmartin1ee7
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-nickmartin1ee7
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/nickmartin1ee7"
